name: Staging CI/CD

on:
  push:
    branches: ['staging']

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP: 'faap-staging'

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: '19.3.0'
        cache: 'yarn'

    - name: Install gem dependencies
      run: bundle install

    - name: Install yarn dependencies
      run: yarn install

  Unit_Tests:
    needs: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Run RSpec tests
      run: bundle exec rspec
      continue-on-error: false

    - name: Run Cucumber tests
      run: bundle exec cucumber --format progress --tags 'not @skip' -q
      continue-on-error: false

  Deploy:
    needs: [Setup, Unit_Tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: '19.3.0'
        cache: 'yarn'
    
    - name: Install gem dependencies
      run: bundle install
    
    - name: Install yarn dependencies
      run: yarn install

    - name: Add heroku credentials
      run: |
        echo -e "machine api.heroku.com\n  login elitracy@tamu.edu\n  password $HEROKU_API_KEY" >> ~/.netrc
        echo -e "machine git.heroku.com\n  login elitracy@tamu.edu\n  password $HEROKU_API_KEY" >> ~/.netrc
    
    - name: Add heroku remote
      run: heroku git:remote -a $HEROKU_APP

    - name: Deploy to Heroku
      run: git push heroku staging:main

    - name: Migrate & Seed Heroku
      run: |
        heroku run rails db:migrate -a $HEROKU_APP
        heroku run rails db:seed -a $HEROKU_APP

