name: CI

on:
  push:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Install gem dependencies
      run: bundle install
    - name: Install yarn dependencies
      run: yarn install

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Run Cucumber tests
      run: bundle exec cucumber --format progress --tags 'not @skip'

    - name: Check exit code
      run: exit ${{ job.status == 'success' }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Install gem dependencies
      run: bundle install

    - name: Install yarn dependencies
      run: yarn install

    - name: Login to Heroku
      run: heroku auth:token $HEROKU_API_KEY
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Add heroku remote
      run: heroku git:remote -a 'fighting-aggies-platform' 

    - name: Deploy to Heroku
      run: git push heroku main

    - name: Migrate Heroku
      run: heroku run rails db:migrate -a 'fighting-aggies-platform'

    - name: Seed Heroku
      run: heroku run rails db:seed -a 'fighting-aggies-platform'
